forum/content/urls.py
from django.urls import path
from . import views

app_name = 'content'

urlpatterns = [
    path(
        'create-subject/',
        views.SubjectCreateView.as_view(),
        name='create_subject'
    ),
    path(
        'create-message/<int:subject_id>/<slug:subject_slug>/',
        views.MessageCreateView.as_view(),
        name='create_message'
    ),
    path(
        '',
        views.SectionListView.as_view(),
        name='section_list'
    ),
    path(
        'search-result/',
        views.FindSubjectListView.as_view(),
        name='search_result'
    ),
    path(
        '<slug:section_slug>/',
        views.SubjectListView.as_view(),
        name='subject_list_by_section'
    ),
    path(
        '<slug:section_slug>/<int:subject_id>/<slug:subject_slug>/',
        views.MessageListView.as_view(),
        name='list_message_by_subject'
    ),
    path(
        'create-update-content/<int:message_id>/',
        views.ContentCreateUpdateView.as_view(),
        name='create_update_content'
    ),
    path(
        'delete-content/<int:content_id>/',
        views.ContentDeleteView.as_view(),
        name='delete_content'
    ),
]

forum/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('content.urls', namespace='content')),
    path('account/', include('account.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/content/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import User
from django.urls import reverse
from slugify import slugify
from django.utils import timezone
from .validators import check_max_size_file, url_video_validator

# Create your models here.
class Section(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'Section'
        verbose_name_plural = 'Sections'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('content:subject_list_by_section', args=[self.slug])

class Subject(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='subjects'
    )
    section = models.ForeignKey(
        Section,
        on_delete=models.CASCADE,
        related_name='subjects',
    )
    name = models.CharField(max_length=250)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]
        verbose_name = 'Subject'
        verbose_name_plural = 'Subject'
        unique_together = ('id', 'slug')

    def __str__(self):
        return self.name  

    def get_absolute_url(self):
        return reverse('content:list_message_by_subject', args=[
            self.section.slug,
            self.id,
            self.slug
        ]) 

    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs) 
    
class SubjectView(models.Model):
    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
        related_name='views'
    )
    date = models.DateField()
    views = models.PositiveSmallIntegerField()

    class Meta:
        ordering = ['date']

class Message(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='author_message',
        null=True
    )
    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    parent_message = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='answer_messages',
        blank=True,
        null=True
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'Message form {self.author}'

class Content(models.Model):
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name='contents'
    )
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        related_name='messages',
        limit_choices_to={'model__in': ('text', 'video', 'image')}
    )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Text(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

class Image(models.Model):
    file = models.FileField(upload_to='images', validators=[check_max_size_file])

class Video(models.Model):
    video = models.URLField(validators=[url_video_validator])

forum/content/forms.py
from django import forms
from .models import Section, Subject, Text

class SubjectForm(forms.ModelForm):

    class Meta:
        model = Subject
        fields = ['name', 'section']

class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ['text']

forum/content/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, DeleteView
from django.views.generic.base import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Section, Subject, Message, Content
from .forms import SubjectForm, TextForm
from django.forms import modelform_factory
from django.conf import settings
from django.apps import apps
from .tasks import task_send_mail
from django.core.cache import cache
import redis

r = redis.Redis(
    host=settings.REDIS_HOST,
    port=settings.REDIS_PORT,
    db=settings.REDIS_DB
)

# Create your views here.
class SectionListView(ListView):
    template_name = 'section/section_list.html'
    model = Section
    context_object_name = 'sections'

    def get_queryset(self) -> QuerySet[Any]:
        
        cache_section_list = cache.get('section_list')
        if cache_section_list:
            return cache_section_list
        
        section_list = super().get_queryset().filter(active=True)
        cache.set('section_list', section_list, 60 * 60)

        return section_list
    
class SubjectListView(ListView):
    model = Subject
    template_name = 'subject/subject_list.html'
    context_object_name = 'subjects'
    section = None

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:

        section_slug = self.kwargs['section_slug']
        self.section = get_object_or_404(
            Section,
            slug=section_slug
        )

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['section'] = self.section

        for subject in context['subjects']:
            subject.total_views = r.get(f'subject:{subject.id}:views')
            subject.total_views = int(subject.total_views) if subject.total_views else 0

        return context
    
    def get_queryset(self) -> QuerySet[Any]:

        cache_subject_list = cache.get(f'subject_list:{self.section.id}')
        if cache_subject_list:
            return cache_subject_list

        subject_list = super().get_queryset() \
            .filter(active=True, section__slug=self.kwargs['section_slug'])
        cache.set(f'subject_list:{self.section.id}', subject_list, 60 * 60)

        return subject_list
    
class MessageCreateView(LoginRequiredMixin, View):
    template_name = 'manage/create_message.html'
    subject_obj = None
    parent_message = None
    has_permission = True

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        
        if 'text_form' not in context:
            context['text_form'] = TextForm()
        if 'subject' not in context:
            context['subject'] = self.subject_obj
        if 'parent_message' not in context:
            context['parent_message'] = self.parent_message

        return context

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        subject_id = self.kwargs['subject_id']
        subject_slug = self.kwargs['subject_slug'] 
        
        self.subject_obj = get_object_or_404(
            Subject,
            id=subject_id,
            slug=subject_slug
        )

        parent_message_id = request.GET.get('id')
        if parent_message_id:
            self.parent_message = get_object_or_404(
                    Message,
                    id=parent_message_id
                )
            
            if self.parent_message.subject != self.subject_obj:
                self.has_permission = False

        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if not self.has_permission:
            return redirect(self.subject_obj.get_absolute_url())
        return super().get(request, *args, **kwargs)
    
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:        

        if self.subject_obj:
            text_form = TextForm(request.POST)

            if text_form.is_valid():
                text_obj = text_form.save()

                if self.parent_message:
                    task_send_mail.delay(request.user.id, self.parent_message.id)

                message = Message.objects.create(
                    author=request.user,
                    subject=self.subject_obj,
                    parent_message=self.parent_message
                )
                Content.objects.create(
                    message=message,
                    item=text_obj
                )

                return redirect(self.subject_obj.get_absolute_url())
            
            return self.render_to_response(self.get_context_data(
                text_form=text_form,
                parent_message=self.parent_message
            ))
        
        return redirect('content:not_found')
    
class SubjectCreateView(LoginRequiredMixin, View):
    template_name = 'manage/create_subject.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        
        if 'subject_form' not in context:
            context['subject_form'] = SubjectForm()
        if 'text_form' not in context:
            context['text_form'] = TextForm()

        return context
    
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        
        subject_form = SubjectForm(request.POST)
        text_form = TextForm(request.POST)

        if subject_form.is_valid() and text_form.is_valid():
            text_obj = text_form.save()
            subject_obj = subject_form.save(commit=False)

            subject_obj.author = request.user
            subject_obj.save()
            
            message = Message.objects.create(
                author=request.user,
                subject=subject_obj,
            )     
            Content.objects.create(
                message=message,
                item=text_obj
            )

            
            return redirect(subject_obj.get_absolute_url())
        
        return self.render_to_response(self.get_context_data(
            subject_form=subject_form,
            text_form=text_form,
        ))
    
class MessageListView(ListView):
    template_name = 'message/list_message_by_subject.html'
    context_object_name = 'messages'
    model = Message

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        subject_id = self.kwargs['subject_id']
        r.incr(f'subject:{subject_id}:views')
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Any]:

        section_slug = self.kwargs['section_slug']
        subject_slug = self.kwargs['subject_slug']
        subject_id = self.kwargs['subject_id']

        cache_message_list = cache.get(f'message_list:{subject_id}:{subject_slug}')
        if cache_message_list:
            return cache_message_list

        message_list = super().get_queryset().filter(
            subject__section__slug=section_slug,
            subject_id=subject_id,
            subject__slug=subject_slug,
        )
        cache.set(f'message_list:{subject_id}:{subject_slug}', message_list, 60 * 60)

        return message_list
    
class ContentCreateUpdateView(LoginRequiredMixin, View):
    template_name = 'content/create_update_content.html'
    model = None
    message = None
    object = None
    has_permission = False

    def get_model(self, name_model):
        if name_model in ['text', 'image', 'video']:
            return apps.get_model(
                'content',
                model_name=name_model
            )
        
        return None
    
    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model, fields='__all__')
        
        return Form(*args, **kwargs)
    
    def dispatch(self, request: HttpRequest, message_id, *args: Any, **kwargs: Any) -> HttpResponse:
        self.message = get_object_or_404(
            Message,
            id=message_id
        )
        
        name_model = request.GET.get('content')
        object_id = request.GET.get('id')
        if object_id:
            self.object = get_object_or_404(
                Content,
                id=object_id
            )

            if self.object.message.author == request.user \
                and self.object.content_type.model == name_model:
                self.has_permission = True

        self.model = self.get_model(name_model)

        if self.message.author == request.user and not self.object:
            self.has_permission = True
        
        if self.message.author != request.user and self.object:
            self.has_permission = False

        return super().dispatch(request, message_id, *args, **kwargs)
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if not self.has_permission:
            return redirect(self.message.subject.get_absolute_url())
        
        form = self.get_form(
            self.model,
            instance = self.object.item if self.object else None
        )

        return self.render_to_response(self.get_context_data(
            form=form,
            object=self.object
        )) 
    
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        form = self.get_form(
            self.model, 
            instance=self.object.item if self.object else None,
            data=request.POST,
            files=request.FILES
        )

        if form.is_valid():

forum/content/templates/message/list_message_by_subject.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %}

{% block title %}{{ messages.first.subject.name }}{% endblock %}

{% block content %}
    <div class="ms-4 me-4">
        <div class="position-relative mx-auto" style="width: 700px; height: 70px;">
            <h3 class="position-absolute top-50 start-50 translate-middle">{{ messages.first.subject.section.name }}</h3>
        </div>
        <h2>{{ messages.first.subject.name }}</h2>
        <a class="btn btn-outline-secondary m-3" href="{% url 'content:create_message' messages.first.subject.id messages.first.subject.slug %}">Добавить сообщение</a>
        {% for message in messages %}
            <table class="table">
                <tbody class="border">
                    <tr>
                        <td class="border" style="width: 200px;">
                            <a class="nav-link active" aria-current="page" href="#">
                                <img src="{{ message.author.profile.photo.url }}" class="rounded mx-auto d-block" alt="default-photo">
                            </a>
                            <a class="nav-link active pt-4 ps-3" aria-current="page">
                                {% if message.author.first_name and message.author.last_name %}
                                    {{ message.author.first_name }} {{ message.author.last_name }}
                                {% else %}
                                    {{ message.author }}
                                {% endif %}
                            </a>
                        </td>
                        {% with user=request.user %}
                        <td>
                            <div>
                                {% with parent_message=message.parent_message %}
                                    {% if parent_message %}
                                        <p class="fw-bold">Ответ пользователю: {{ parent_message.author }}</p>
                                    {% endif %}
                                    {% for content in message.contents.all %}
                                    <div>
                                        {% with model_name=content.content_type.model %}
                                        <div class="fs-6 fw-light">
                                            {% if content.updated > content.created %}
                                                Изменено {{ content.updated }}
                                            {% else %}
                                                Добавлено {{ content.created }}  
                                            {% endif %}
                                            {% if user == message.author %}
                                            <a href="{% url 'content:create_update_content' message.id %}?content={{ model_name }}&id={{ content.id }}">
                                                <img src="{% static 'img/edit.png' %}" style="max-width: 20px;" alt="edit-content">
                                            </a>
                                            {% if forloop.counter != 1 %}
                                                <a href="{% url 'content:delete_content' content.id %}">
                                                    <img src="{% static 'img/delete.png' %}" style="max-width: 20px;" alt="delete-content">
                                                </a>
                                            {% endif %}
                                            {% endif %}
                                        </div>
                                        {% if model_name == 'text' %}
                                            {{ content.item.text|linebreaks }}
                                        {% elif model_name == 'image' %}
                                        <p>
                                            <img src="{{ content.item.file.url }}" style="max-width: 250px;">
                                        </p>
                                        {% else %}
                                            {% video content.item.video "small" %}
                                        {% endif %}
                                        {% endwith %}
                                    </div>
                                    {% endfor %}
                                {% endwith %}
                            </div>
                        </td>
                    </tr>
                    <tr>
                            <td class="border">Опубликовано: {{ message.created }}</td>
                            <td class="border">
                                <a class="btn btn-outline-secondary" href="{% url 'content:create_message' message.subject.id message.subject.slug %}?id={{ message.id }}">Ответить на сообщение</a>
                            </td>
                            {% if user.is_authenticated and message.author == user %}
                                <td class="border">
                                    <li class="btn btn-outline-secondary">
                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                            aria-expanded="false">
                                            Добавить контент
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="{% url 'content:create_update_content' message.id %}?content=text">Текст</a></li>
                                            <li><a class="dropdown-item" href="{% url 'content:create_update_content' message.id %}?content=image">Изображение</a></li>
                                            <li><a class="dropdown-item" href="{% url 'content:create_update_content' message.id %}?content=video">Видео</a></li>
                                        </ul>
                                    </li>
                                </td>
                            {% endif %}
                        {% endwith %}
                    </tr>
                </tbody>
            </table>
        {% endfor %}
    </div>
{% endblock %}